import { onAuthStateChanged, signOut } from "https://www.gstatic.com/firebasejs/12.19.0/firebase-auth.js";
import { doc, getDoc } from "https://www.gstatic.com/firebasejs/12.19.0/firebase-firestore.js";
import { auth, db } from "./firebase.js";
import { carregarConteudos } from "./conteudos.js";
import { personalizarConteudos } from "./personalizacao.js";
import { listarFavoritos, listarProgresso } from "./biblioteca-usuario.js";
import { criarBotaoFavorito } from "./interface-biblioteca.js";

const app=document.querySelector("[data-juices-app]");const loading=document.querySelector("[data-juices-loading]");const grid=document.querySelector("[data-juices-grid]");const empty=document.querySelector("[data-juices-empty]");const logout=document.querySelector("[data-logout]");const headerName=document.querySelector("[data-header-name]");const userInitial=document.querySelector("[data-user-initial]");const chips=document.querySelector("[data-juices-profile-chips]");let favoriteIds=new Set();let progressMap=new Map();
const make=(tag,cls,text)=>{const el=document.createElement(tag);if(cls)el.className=cls;if(text!==undefined)el.textContent=text;return el};
const setMedia=(slot,url,label,alt)=>{if(url){slot.classList.add("has-image");slot.style.backgroundImage=`linear-gradient(135deg,rgba(38,62,50,.02),rgba(38,62,50,.10)),url("${String(url).replaceAll('"','%22')}")`;slot.setAttribute("role","img");slot.setAttribute("aria-label",alt||label)}else{slot.append(make("span","",label),make("small","","Espaço reservado para a imagem."))}};
const render=(userId,items)=>{grid.innerHTML="";items.forEach(item=>{const card=make("article","juice-card");const recommended=item.personalizacao?.recomendado&&!item.personalizacao?.bloqueado;card.classList.toggle("is-profile-match",Boolean(recommended));const media=make("div","juice-card-media");const ingredients=make("div","juice-media-slot");setMedia(ingredients,item.midia?.imagem_ingredientes_url,"INGREDIENTES",item.midia?.imagem_ingredientes_alt);const ready=make("div","juice-media-slot");setMedia(ready,item.midia?.imagem_pronto_url||item.imagem_url,"SUCO PRONTO",item.midia?.imagem_pronto_alt||item.imagem_alt);const fav=criarBotaoFavorito({usuarioId:userId,item,favoritos:favoriteIds,className:"juice-card-favorite"});ready.append(fav);media.append(ingredients,ready);const body=make("div","juice-card-body");const meta=make("div","juice-card-meta");meta.append(make("span","","SUCO DETOX"));if(recommended)meta.append(make("i","","Do seu perfil"));body.append(meta,make("h3","",item.titulo),make("p","",item.resumo));const facts=make("div","juice-card-facts");[item.experiencia?.tempo,item.experiencia?.dificuldade,item.rendimento].filter(Boolean).slice(0,3).forEach(v=>facts.append(make("span","",v)));body.append(facts);const progress=progressMap.get(item.id);if(progress)body.append(make("span","juice-card-progress",progress.status==="concluido"?"✓ Concluído":`${Number(progress.progresso||0)}% explorado`));const link=make("a","juice-open","Ver receita completa →");link.href=`./conteudo.html?id=${encodeURIComponent(item.id)}`;body.append(link);card.append(media,body);grid.append(card)});empty.hidden=items.length>0};
const renderProfile=(profile)=>{chips.innerHTML="";const values=[profile.perfil_alimentar,profile.tempo_preparo,...(Array.isArray(profile.interesses_alimentares)?profile.interesses_alimentares:[])].filter(Boolean).slice(0,4);values.forEach(value=>chips.append(make("span","",String(value).replaceAll("_"," "))))};
logout?.addEventListener("click",async()=>{try{await signOut(auth)}finally{location.replace("./login.html")}});
onAuthStateChanged(auth,async user=>{if(!user){location.replace("./login.html");return}try{const [u,p,c]=await Promise.all([getDoc(doc(db,"usuarios",user.uid)),getDoc(doc(db,"perfis",user.uid)),carregarConteudos("receita")]);const userData=u.exists()?u.data():{};const profile=p.exists()?p.data():{};const allowed=(userData.status_acesso==="ativo"&&userData.status_pagamento==="pago")||(profile.acesso_teste===true&&profile.pagamento_teste_status==="aprovado");if(!allowed){location.replace("./pagamento.html");return}const [f,pr]=await Promise.allSettled([listarFavoritos(user.uid),listarProgresso(user.uid)]);if(f.status==="fulfilled")favoriteIds=new Set(f.value.map(x=>x.conteudo_id||x.id));if(pr.status==="fulfilled")progressMap=new Map(pr.value.map(x=>[x.conteudo_id||x.id,x]));const juices=personalizarConteudos(c.itens.filter(item=>item.categoria==="suco_detox"),profile);render(user.uid,juices);renderProfile(profile);const name=userData.nome||user.displayName?.split(/\s+/)[0]||"Usuário";if(headerName)headerName.textContent=name;if(userInitial)userInitial.textContent=name.charAt(0).toUpperCase();loading.hidden=true;app.hidden=false}catch(error){console.error("Erro ao carregar Sucos Detox:",error);location.replace("./portal.html")}});
